### ISSUE TITLE
>100% Accuracy

### ISSUE THREAD

**Issue by VoltCruelerz** [etriebe/combat-estimate#8]
The accuracy formula seems to not be bounded appropriately as you can't have >100% accuracy (as seen on Farrock's trident, circled below, and Finnian's spellbook).

<img width="1607" alt="image" src="https://user-images.githubusercontent.com/4068550/167318907-cf4c8528-67f7-443f-aae0-7326c7b5f7ac.png">

**Comment by etriebe** [comment]
I think this should be resolved already with 1.0.10. Can you upgrade and try again?

--Eric Triebe

________________________________
From: Michael Greene ***@***.***>
Sent: Sunday, May 8, 2022 3:46:05 PM
To: etriebe/combat-estimate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [etriebe/combat-estimate] Natural 1 Accuracy (Issue #8)


The accuracy formula seems erroneous, which I assume is due to not accounting for natural 1s being automatic misses.

[image]<https://user-images.githubusercontent.com/4068550/167318907-cf4c8528-67f7-443f-aae0-7326c7b5f7ac.png>

**Comment by VoltCruelerz** [comment]
Ah, yep. That did it. Closing.

**Comment by etriebe** [comment]
All good! It had *just* released! Glad it's resolved.

--Eric Triebe

________________________________
